factionInfos = [];

//Define constant suffix for factions building
c_db = "_db";

#include "object_db\2035_AAF.sqf"
#include "object_db\2035_Rebels.sqf"
#include "object_db\2035_CSAT.sqf"
#include "object_db\2035_FIA.sqf"
#include "object_db\2035_NATO.sqf"
#include "object_db\2035_NATO_FS.sqf"
#include "object_db\2035_NATO_Recon.sqf"
#include "object_db\2035_Spetsnaz.sqf"
#include "object_db\Syndikat.sqf"
#include "object_db\USA.sqf"
#include "object_db\USA_Winter.sqf"
#include "object_db\French.sqf"
#include "object_db\Russian.sqf"
#include "object_db\Takistani.sqf"
#include "object_db\USA_2000.sqf"
#include "object_db\WWII_Wehrmacht.sqf"
#include "object_db\WWII_URSS.sqf"
#include "object_db\WWII_UK.sqf"
#include "object_db\WWII_USA.sqf"
#include "object_db\WWII_FFI.sqf"
#include "object_db\USA_2000_DF.sqf"
#include "object_db\Russian_Winter.sqf"
#include "object_db\Chernarussian_Winter.sqf"
#include "object_db\PMC.sqf"
#include "object_db\Takistani_army.sqf"
#include "object_db\HorizonIsland.sqf"
#include "object_db\HorizonIslandSF.sqf"
#include "object_db\ColdWar_ARVN.sqf"
#include "object_db\ColdWar_NVA.sqf"
#include "object_db\ColdWar_USA.sqf"
#include "object_db\ColdWar_VC.sqf"
#include "object_db\ColdWar_USA_SF.sqf"
#include "object_db\ColdWar_OTAN.sqf"
#include "object_db\ColdWar_USSR.sqf"
#include "object_db\KORSAC_KDF.sqf"
#include "object_db\KORSAC_KS.sqf"
#include "object_db\KORSAC_KFL.sqf"
#include "object_db\KORSAC_KAL.sqf"
#include "object_db\USA_2020.sqf"
#include "object_db\USA_SOCOM_2020.sqf"
#include "object_db\RU_2020.sqf"
#include "object_db\RU_2020_reservists.sqf"